import { Job, Person } from "@/types";

export const jobs: Job[] = Array.from({ length: 8 }).map((_, i) => ({
  id: `job-${i + 1}`,
  title: "Marketing Manager",
  company: "Digital Agency",
  verified: true,
  remote: true,
  employment: "Full-time",
  salary: "$1500 - $2500 / month",
  tags: ["Marketing", "SMM", "Analytics", "Strategy"],
  spotsLeft: 3,
  applied: 7,
  totalSlots: 10,
}));

export const people: Person[] = [
  {
    id: "samantha-lee",
    name: "Samantha Lee",
    role: "Content Creator",
    handle: "@samanthalee",
    platform: "x",
    location: "New York, USA",
    skills: ["Content Creation", "Video Editing", "Marketing", "Copywriting"],
    activelyLooking: true,
    about:
      "Content creator focused on lifestyle and marketing storytelling, helping brands turn everyday moments into scroll-stopping content.",
    niche: "Lifestyle",
    language: "English",
    contentType: "Reviews, Vlogs, Collaborations",
    experience: "4+ years",
    email: "samantha@creatorhub.com",
    website: "https://samanthalee.co",
    responseRate: "97%",
    responseTime: "Within a few hours",
    memberSince: "Mar 2022",
    profileViews: "2,310",
    completedDeals: 52,
    socials: [
      { platform: "X (Twitter)", handle: "@samanthalee" },
      { platform: "Instagram", handle: "@samanthalee" },
      { platform: "TikTok", handle: "@samanthalee" },
    ],
    totalFollowers: "980K",
    engagementRate: "5.1%",
    avgViews: "210K",
    avgLikes: "9.8K",
    avgComments: "260",
    topCountries: [
      { name: "United States", pct: 42 },
      { name: "Canada", pct: 15 },
      { name: "United Kingdom", pct: 12 },
      { name: "Australia", pct: 8 },
      { name: "Germany", pct: 6 },
    ],
    audienceAge: [
      { label: "13-17", pct: 6, color: "#93C5FD" },
      { label: "18-24", pct: 34, color: "#A78BFA" },
      { label: "25-34", pct: 38, color: "#2563EB" },
      { label: "35-44", pct: 15, color: "#F472B6" },
      { label: "45+", pct: 7, color: "#F9A8D4" },
    ],
    audienceGender: { male: 34, female: 66 },
    featuredVideo: {
      title: "A Week in My Creator Life",
      views: "180K",
      likes: "8.4K",
      comments: "410",
    },
  },
  {
    id: "michael-brown",
    name: "Michael Brown",
    role: "Lifestyle Influencer",
    handle: "@michaelb",
    platform: "instagram",
    location: "Los Angeles, USA",
    skills: ["Branding", "Social Media", "SMM", "Photography"],
    activelyLooking: true,
    about:
      "Lifestyle influencer partnering with brands on branding and social campaigns that feel native to the feed, not like ads.",
    niche: "Lifestyle & Branding",
    language: "English",
    contentType: "Photo campaigns, Reels, Brand deals",
    experience: "6+ years",
    email: "michael@brownmedia.com",
    website: "https://michaelbrown.media",
    responseRate: "92%",
    responseTime: "Within a day",
    memberSince: "Jul 2021",
    profileViews: "3,140",
    completedDeals: 71,
    socials: [
      { platform: "Instagram", handle: "@michaelb" },
      { platform: "YouTube", handle: "/michaelbrown" },
      { platform: "TikTok", handle: "@michaelb" },
    ],
    totalFollowers: "1.4M",
    engagementRate: "4.2%",
    avgViews: "300K",
    avgLikes: "14K",
    avgComments: "380",
    topCountries: [
      { name: "United States", pct: 47 },
      { name: "Mexico", pct: 13 },
      { name: "Brazil", pct: 10 },
      { name: "Spain", pct: 7 },
      { name: "Canada", pct: 6 },
    ],
    audienceAge: [
      { label: "13-17", pct: 5, color: "#93C5FD" },
      { label: "18-24", pct: 30, color: "#A78BFA" },
      { label: "25-34", pct: 40, color: "#2563EB" },
      { label: "35-44", pct: 18, color: "#F472B6" },
      { label: "45+", pct: 7, color: "#F9A8D4" },
    ],
    audienceGender: { male: 48, female: 52 },
    featuredVideo: {
      title: "My Morning Routine as a Creator",
      views: "265K",
      likes: "11K",
      comments: "290",
    },
  },
  {
    id: "emma-davis",
    name: "Emma Davis",
    role: "YouTuber",
    handle: "@emmadavis",
    platform: "youtube",
    location: "Miami, USA",
    skills: ["Video Production", "Editing", "Storytelling", "SEO"],
    activelyLooking: true,
    about:
      "YouTuber producing long-form video essays and product deep dives with a strong focus on storytelling and retention.",
    niche: "Entertainment",
    language: "English",
    contentType: "Long-form videos, Unboxings, Interviews",
    experience: "5+ years",
    email: "emma@davisstudio.com",
    website: "https://emmadavis.tv",
    responseRate: "89%",
    responseTime: "Within a day",
    memberSince: "Jan 2020",
    profileViews: "4,020",
    completedDeals: 63,
    socials: [
      { platform: "YouTube", handle: "/emmadavis" },
      { platform: "Instagram", handle: "@emmadavis" },
      { platform: "X (Twitter)", handle: "@emmadavis" },
    ],
    totalFollowers: "2.1M",
    engagementRate: "6.0%",
    avgViews: "410K",
    avgLikes: "22K",
    avgComments: "1.1K",
    topCountries: [
      { name: "United States", pct: 39 },
      { name: "United Kingdom", pct: 16 },
      { name: "India", pct: 11 },
      { name: "Canada", pct: 9 },
      { name: "Australia", pct: 6 },
    ],
    audienceAge: [
      { label: "13-17", pct: 9, color: "#93C5FD" },
      { label: "18-24", pct: 33, color: "#A78BFA" },
      { label: "25-34", pct: 36, color: "#2563EB" },
      { label: "35-44", pct: 15, color: "#F472B6" },
      { label: "45+", pct: 7, color: "#F9A8D4" },
    ],
    audienceGender: { male: 44, female: 56 },
    featuredVideo: {
      title: "I Tried Every Productivity App for 30 Days",
      views: "402K",
      likes: "19K",
      comments: "980",
    },
  },
  {
    id: "daniel-clark",
    name: "Daniel Clark",
    role: "Tech Reviewer",
    handle: "@danieltech",
    platform: "x",
    location: "Austin, USA",
    skills: ["Tech Review", "Video Editing", "Writing", "Benchmarking"],
    activelyLooking: true,
    about:
      "Tech reviewer and content creator with a passion for making the latest technology reviews, tutorials, and comparisons that help my audience make informed decisions.",
    niche: "Technology",
    language: "English",
    contentType: "Reviews, Tutorials, Comparisons",
    experience: "5+ years",
    email: "daniel@techreviews.com",
    website: "https://danieltech.com",
    responseRate: "95%",
    responseTime: "Within a few hours",
    memberSince: "Jan 2023",
    profileViews: "1,245",
    completedDeals: 38,
    socials: [
      { platform: "X (Twitter)", handle: "@danieltech" },
      { platform: "YouTube", handle: "/danieltech" },
      { platform: "Instagram", handle: "@danieltech" },
      { platform: "TikTok", handle: "@danieltech" },
    ],
    totalFollowers: "1.2M",
    engagementRate: "4.8%",
    avgViews: "250K",
    avgLikes: "12K",
    avgComments: "320",
    topCountries: [
      { name: "United States", pct: 35 },
      { name: "India", pct: 18 },
      { name: "United Kingdom", pct: 10 },
      { name: "Canada", pct: 7 },
      { name: "Australia", pct: 5 },
    ],
    audienceAge: [
      { label: "13-17", pct: 8, color: "#93C5FD" },
      { label: "18-24", pct: 28, color: "#A78BFA" },
      { label: "25-34", pct: 42, color: "#2563EB" },
      { label: "35-44", pct: 16, color: "#F472B6" },
      { label: "45+", pct: 6, color: "#F9A8D4" },
    ],
    audienceGender: { male: 72, female: 28 },
    featuredVideo: {
      title: "iPhone 15 Pro Max Review: Is It Worth It?",
      views: "125K",
      likes: "3.2K",
      comments: "320",
    },
  },
  {
    id: "olivia-martinez",
    name: "Olivia Martinez",
    role: "Fashion Blogger",
    handle: "@oliviamtz",
    platform: "instagram",
    location: "Chicago, USA",
    skills: ["Fashion", "Photography", "Styling", "Brand Partnerships"],
    activelyLooking: true,
    about:
      "Fashion blogger and stylist creating seasonal lookbooks and outfit breakdowns for brands entering the US market.",
    niche: "Fashion",
    language: "English",
    contentType: "Lookbooks, Reels, Styling guides",
    experience: "4+ years",
    email: "olivia@martinezstyle.com",
    website: "https://oliviamartinez.style",
    responseRate: "94%",
    responseTime: "Within a day",
    memberSince: "May 2022",
    profileViews: "2,780",
    completedDeals: 47,
    socials: [
      { platform: "Instagram", handle: "@oliviamtz" },
      { platform: "TikTok", handle: "@oliviamtz" },
      { platform: "Pinterest", handle: "@oliviamartinez" },
    ],
    totalFollowers: "860K",
    engagementRate: "5.6%",
    avgViews: "150K",
    avgLikes: "9.1K",
    avgComments: "245",
    topCountries: [
      { name: "United States", pct: 40 },
      { name: "France", pct: 12 },
      { name: "Italy", pct: 10 },
      { name: "United Kingdom", pct: 9 },
      { name: "Canada", pct: 7 },
    ],
    audienceAge: [
      { label: "13-17", pct: 7, color: "#93C5FD" },
      { label: "18-24", pct: 36, color: "#A78BFA" },
      { label: "25-34", pct: 37, color: "#2563EB" },
      { label: "35-44", pct: 14, color: "#F472B6" },
      { label: "45+", pct: 6, color: "#F9A8D4" },
    ],
    audienceGender: { male: 22, female: 78 },
    featuredVideo: {
      title: "Fall Capsule Wardrobe Lookbook",
      views: "142K",
      likes: "8.9K",
      comments: "310",
    },
  },
  {
    id: "james-wilson",
    name: "James Wilson",
    role: "TikTok Creator",
    handle: "@jameswilson",
    platform: "tiktok",
    location: "Atlanta, USA",
    skills: ["Short Videos", "Content Creation", "SMM", "Trends"],
    activelyLooking: true,
    about:
      "TikTok creator turning trending sounds and formats into branded short-form content that actually gets watched to the end.",
    niche: "Entertainment",
    language: "English",
    contentType: "Short-form videos, Skits, Trends",
    experience: "3+ years",
    email: "james@wilsonshorts.com",
    website: "https://jameswilson.link",
    responseRate: "91%",
    responseTime: "Within a day",
    memberSince: "Sep 2023",
    profileViews: "1,890",
    completedDeals: 29,
    socials: [
      { platform: "TikTok", handle: "@jameswilson" },
      { platform: "Instagram", handle: "@jameswilson" },
    ],
    totalFollowers: "3.2M",
    engagementRate: "7.4%",
    avgViews: "600K",
    avgLikes: "48K",
    avgComments: "1.4K",
    topCountries: [
      { name: "United States", pct: 44 },
      { name: "Philippines", pct: 12 },
      { name: "United Kingdom", pct: 9 },
      { name: "Canada", pct: 8 },
      { name: "Nigeria", pct: 6 },
    ],
    audienceAge: [
      { label: "13-17", pct: 22, color: "#93C5FD" },
      { label: "18-24", pct: 41, color: "#A78BFA" },
      { label: "25-34", pct: 24, color: "#2563EB" },
      { label: "35-44", pct: 9, color: "#F472B6" },
      { label: "45+", pct: 4, color: "#F9A8D4" },
    ],
    audienceGender: { male: 51, female: 49 },
    featuredVideo: {
      title: "POV: Your Brand Deal Goes Viral",
      views: "1.1M",
      likes: "90K",
      comments: "2.3K",
    },
  },
  {
    id: "sophia-johnson",
    name: "Sophia Johnson",
    role: "Travel Blogger",
    handle: "@sophiajohnson",
    platform: "instagram",
    location: "Seattle, USA",
    skills: ["Travel", "Photography", "Storytelling", "SEO"],
    activelyLooking: true,
    about:
      "Travel blogger documenting slow-travel itineraries and destination guides for brands in tourism and outdoor gear.",
    niche: "Travel",
    language: "English",
    contentType: "Guides, Reels, Photo essays",
    experience: "6+ years",
    email: "sophia@wanderjohnson.com",
    website: "https://sophiajohnson.travel",
    responseRate: "96%",
    responseTime: "Within a few hours",
    memberSince: "Feb 2021",
    profileViews: "3,510",
    completedDeals: 58,
    socials: [
      { platform: "Instagram", handle: "@sophiajohnson" },
      { platform: "YouTube", handle: "/sophiajohnson" },
    ],
    totalFollowers: "740K",
    engagementRate: "5.0%",
    avgViews: "190K",
    avgLikes: "7.6K",
    avgComments: "210",
    topCountries: [
      { name: "United States", pct: 33 },
      { name: "Germany", pct: 14 },
      { name: "United Kingdom", pct: 12 },
      { name: "Netherlands", pct: 9 },
      { name: "Canada", pct: 8 },
    ],
    audienceAge: [
      { label: "13-17", pct: 4, color: "#93C5FD" },
      { label: "18-24", pct: 27, color: "#A78BFA" },
      { label: "25-34", pct: 41, color: "#2563EB" },
      { label: "35-44", pct: 20, color: "#F472B6" },
      { label: "45+", pct: 8, color: "#F9A8D4" },
    ],
    audienceGender: { male: 37, female: 63 },
    featuredVideo: {
      title: "10 Days Across the Balkans on a Budget",
      views: "205K",
      likes: "8.1K",
      comments: "260",
    },
  },
  {
    id: "liam-taylor",
    name: "Liam Taylor",
    role: "Gaming Streamer",
    handle: "@liamtaylor",
    platform: "youtube",
    location: "Dallas, USA",
    skills: ["Live Streaming", "Gaming", "Community", "Editing"],
    activelyLooking: true,
    about:
      "Gaming streamer and YouTuber building an engaged community around competitive play and gear reviews.",
    niche: "Gaming",
    language: "English",
    contentType: "Streams, Highlights, Gear reviews",
    experience: "7+ years",
    email: "liam@taylorplays.com",
    website: "https://liamtaylor.gg",
    responseRate: "88%",
    responseTime: "Within a day",
    memberSince: "Oct 2019",
    profileViews: "5,120",
    completedDeals: 80,
    socials: [
      { platform: "YouTube", handle: "/liamtaylor" },
      { platform: "Twitch", handle: "liamtaylor" },
      { platform: "X (Twitter)", handle: "@liamtaylor" },
    ],
    totalFollowers: "1.8M",
    engagementRate: "6.6%",
    avgViews: "320K",
    avgLikes: "16K",
    avgComments: "890",
    topCountries: [
      { name: "United States", pct: 41 },
      { name: "Canada", pct: 13 },
      { name: "United Kingdom", pct: 10 },
      { name: "Germany", pct: 8 },
      { name: "Sweden", pct: 6 },
    ],
    audienceAge: [
      { label: "13-17", pct: 18, color: "#93C5FD" },
      { label: "18-24", pct: 39, color: "#A78BFA" },
      { label: "25-34", pct: 30, color: "#2563EB" },
      { label: "35-44", pct: 9, color: "#F472B6" },
      { label: "45+", pct: 4, color: "#F9A8D4" },
    ],
    audienceGender: { male: 81, female: 19 },
    featuredVideo: {
      title: "Ranked Grind: Road to Top 100",
      views: "298K",
      likes: "14K",
      comments: "760",
    },
  },
  {
    id: "ava-anderson",
    name: "Ava Anderson",
    role: "Beauty Influencer",
    handle: "@avaanderson",
    platform: "instagram",
    location: "Phoenix, USA",
    skills: ["Beauty", "Makeup", "Skincare", "Product Reviews"],
    activelyLooking: true,
    about:
      "Beauty influencer sharing makeup tutorials and honest skincare reviews for a mostly Gen Z and millennial audience.",
    niche: "Beauty",
    language: "English",
    contentType: "Tutorials, Reviews, Reels",
    experience: "5+ years",
    email: "ava@andersonbeauty.com",
    website: "https://avaanderson.beauty",
    responseRate: "93%",
    responseTime: "Within a day",
    memberSince: "Apr 2021",
    profileViews: "2,960",
    completedDeals: 65,
    socials: [
      { platform: "Instagram", handle: "@avaanderson" },
      { platform: "TikTok", handle: "@avaanderson" },
      { platform: "YouTube", handle: "/avaanderson" },
    ],
    totalFollowers: "1.1M",
    engagementRate: "5.8%",
    avgViews: "230K",
    avgLikes: "13K",
    avgComments: "410",
    topCountries: [
      { name: "United States", pct: 38 },
      { name: "Mexico", pct: 11 },
      { name: "Brazil", pct: 10 },
      { name: "United Kingdom", pct: 8 },
      { name: "Philippines", pct: 7 },
    ],
    audienceAge: [
      { label: "13-17", pct: 12, color: "#93C5FD" },
      { label: "18-24", pct: 40, color: "#A78BFA" },
      { label: "25-34", pct: 32, color: "#2563EB" },
      { label: "35-44", pct: 12, color: "#F472B6" },
      { label: "45+", pct: 4, color: "#F9A8D4" },
    ],
    audienceGender: { male: 9, female: 91 },
    featuredVideo: {
      title: "Full Face Using Only Drugstore Products",
      views: "220K",
      likes: "12K",
      comments: "390",
    },
  },
  {
    id: "ethan-white",
    name: "Ethan White",
    role: "Fitness Coach",
    handle: "@ethanwhite",
    platform: "tiktok",
    location: "Denver, USA",
    skills: ["Fitness", "Health", "Nutrition", "Coaching"],
    activelyLooking: true,
    about:
      "Fitness coach and content creator sharing training programs and nutrition tips for busy professionals.",
    niche: "Fitness & Health",
    language: "English",
    contentType: "Workouts, Nutrition tips, Transformations",
    experience: "8+ years",
    email: "ethan@whitefit.com",
    website: "https://ethanwhite.fit",
    responseRate: "90%",
    responseTime: "Within a day",
    memberSince: "Jun 2020",
    profileViews: "4,410",
    completedDeals: 74,
    socials: [
      { platform: "TikTok", handle: "@ethanwhite" },
      { platform: "Instagram", handle: "@ethanwhite" },
      { platform: "YouTube", handle: "/ethanwhite" },
    ],
    totalFollowers: "1.6M",
    engagementRate: "6.1%",
    avgViews: "280K",
    avgLikes: "15K",
    avgComments: "520",
    topCountries: [
      { name: "United States", pct: 45 },
      { name: "United Kingdom", pct: 11 },
      { name: "Canada", pct: 10 },
      { name: "Australia", pct: 8 },
      { name: "Germany", pct: 5 },
    ],
    audienceAge: [
      { label: "13-17", pct: 5, color: "#93C5FD" },
      { label: "18-24", pct: 29, color: "#A78BFA" },
      { label: "25-34", pct: 43, color: "#2563EB" },
      { label: "35-44", pct: 17, color: "#F472B6" },
      { label: "45+", pct: 6, color: "#F9A8D4" },
    ],
    audienceGender: { male: 58, female: 42 },
    featuredVideo: {
      title: "The Only 5 Exercises You Actually Need",
      views: "310K",
      likes: "17K",
      comments: "610",
    },
  },
];

export function getPersonById(id: string): Person | undefined {
  return people.find((p) => p.id === id);
}
